In [1]:
import pandas as pd

In [2]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv("MultinomialNB.csv")

In [4]:
df

     Unnamed: 0                                               text     label
0             0    project discussion check now meeting please de…  not spam
1             1  client prize regarding about check report sche...  not spam
2             2                                please update today  not spam
3             3   today regarding urgent client now details report  not spam
4             4                 information prize urgent regarding      spam
..          ...                                                ...       ...
595         595                     money check about free details      spam
596         596  details offer meeting information please about...      spam
597         597           regarding please team urgent now details  not spam
598         598                             check meeting now cash  not spam
599         599    information cash free today win check regarding      spam

[600 rows x 3 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test, y_train,y_test = train_test_split(
    df['text'],df['label'],test_size=0.2,random_state = 42
)

In [8]:
vectorizer = CountVectorizer()
x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

In [9]:
model = MultinomialNB()
model.fit(x_train_vec,y_train)

MultinomialNB()

In [10]:
y_pred = model.predict(x_test_vec)

In [11]:
y_pred

array(['not spam', 'spam', 'spam', 'not spam', 'spam', 'spam', 'spam',
       'not spam', 'not spam', 'spam', 'not spam', 'not spam', 'spam',
       'not spam', 'not spam', 'spam', 'spam', 'spam', 'spam', 'not spam',
       'not spam', 'not spam', 'spam', 'spam', 'not spam', 'not spam',
       'spam', 'spam', 'not spam', 'spam', 'spam', 'not spam', 'spam',
       'not spam', 'spam', 'not spam', 'spam', 'not spam', 'spam',
       'not spam', 'spam', 'spam', 'not spam', 'not spam', 'not spam',
       'not spam', 'spam', 'not spam', 'spam', 'spam', 'spam', 'not spam',
       'spam', 'not spam', 'spam', 'not spam', 'not spam', 'spam',
       'not spam', 'not spam', 'not spam', 'not spam', 'spam', 'not spam',
       'not spam', 'not spam', 'spam', 'not spam', 'not spam', 'not spam',
       'spam', 'spam', 'not spam', 'spam', 'spam', 'spam', 'not spam',
       'spam', 'spam', 'spam', 'spam', 'not spam', 'spam', 'not spam',
       'spam', 'spam', 'spam', 'not spam', 'not spam', 'not spam', 'spam',
       'not spam', 'not spam', 'spam', 'not spam', 'spam', 'spam', 'spam',
       'not spam', 'not spam', 'spam', 'not spam', 'spam', 'not spam',
       'not spam', 'not spam', 'spam', 'spam', 'spam', 'spam', 'spam',
       'not spam', 'not spam', 'spam', 'not spam', 'spam', 'spam',
       'not spam', 'not spam', 'spam'], dtype='<U8')

In [13]:
from sklearn.metrics import accuracy_score

In [14]:
print("Accuracy =", accuracy_score(y_test,y_pred)*100)

Accuracy = 93.33333333333333

In [15]:
results = pd.DataFrame({
    "text" : x_test,
    "Actual" : y_test,
    "Predicted" : y_pred
})
results

                                                  text    Actual Predicted
110             team report urgent now details meeting  not spam  not spam
419               details win now prize free regarding      spam      spam
565                 cash please now prize check update      spam      spam
77                    now meeting please details about  not spam  not spam
181  now free urgent information about today win me...      spam      spam
..                                                 ...       ...       ...
399         schedule please information free bonus now      spam      spam
340       bonus regarding offer cash now details about      spam      spam
148                              please about schedule  not spam  not spam
494                    about regarding project details  not spam  not spam
439                                check win regarding      spam      spam

[120 rows x 3 columns]